# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .get_trigger_url import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_alicloud_fc_url.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_alicloud_fc_url.config')

_utilities.register(
    resource_modules="""
[]
""",
    resource_packages="""
[
 {
  "pkg": "alicloud-fc-url",
  "token": "pulumi:providers:alicloud-fc-url",
  "fqn": "pulumi_alicloud_fc_url",
  "class": "Provider"
 }
]
"""
)
