// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/rhysmdnz/pulumi-alicloud-fc-url/sdk/go/alicloud-fc-url/internal"
)

var _ = internal.GetEnvOrDefault

// Example provider attribute
func GetRegion(ctx *pulumi.Context) string {
	return config.Get(ctx, "alicloud-fc-url:region")
}
