[project]
  name = "pulumi_alicloud_fc_url"
  description = "A Pulumi package for creating and managing alicloud-fc-url cloud resources."
  dependencies = ["parver>=0.2.1", "pulumi>=3.0.0,<4.0.0", "semver>=2.8.1", "typing-extensions>=4.11; python_version < \"3.11\""]
  keywords = ["pulumi", "alicloud-fc-url", "category/cloud"]
  readme = "README.md"
  requires-python = ">=3.8"
  version = "0.0.0"
  [project.license]
    text = "Apache-2.0"
  [project.urls]
    Homepage = "https://www.pulumi.com"
    Repository = "https://github.com/rhysmdnz/pulumi-alicloud-fc-url"

[build-system]
  requires = ["setuptools>=61.0"]
  build-backend = "setuptools.build_meta"

[tool]
  [tool.setuptools]
    [tool.setuptools.package-data]
      pulumi_alicloud_fc_url = ["py.typed", "pulumi-plugin.json"]
