// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package alicloudfcurl

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rhysmdnz/pulumi-alicloud-fc-url/sdk/go/alicloud-fc-url/internal"
)

// Example data source
func GetTriggerUrl(ctx *pulumi.Context, args *GetTriggerUrlArgs, opts ...pulumi.InvokeOption) (*GetTriggerUrlResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetTriggerUrlResult
	err := ctx.Invoke("alicloud-fc-url:index/getTriggerUrl:getTriggerUrl", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTriggerUrl.
type GetTriggerUrlArgs struct {
	// Example identifier
	FunctionName string `pulumi:"functionName"`
	// Example configurable attribute
	ServiceName string `pulumi:"serviceName"`
	// Example identifier
	TriggerName string `pulumi:"triggerName"`
}

// A collection of values returned by getTriggerUrl.
type GetTriggerUrlResult struct {
	Config       string `pulumi:"config"`
	CreationTime string `pulumi:"creationTime"`
	// Example identifier
	FunctionName string `pulumi:"functionName"`
	// The ID of this resource.
	Id                   string `pulumi:"id"`
	InvocationRole       string `pulumi:"invocationRole"`
	LastModificationTime string `pulumi:"lastModificationTime"`
	// Example configurable attribute
	ServiceName string `pulumi:"serviceName"`
	SourceArn   string `pulumi:"sourceArn"`
	// Example identifier
	TriggerName string `pulumi:"triggerName"`
	Type        string `pulumi:"type"`
	UrlInternet string `pulumi:"urlInternet"`
	UrlIntranet string `pulumi:"urlIntranet"`
}

func GetTriggerUrlOutput(ctx *pulumi.Context, args GetTriggerUrlOutputArgs, opts ...pulumi.InvokeOption) GetTriggerUrlResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetTriggerUrlResult, error) {
			args := v.(GetTriggerUrlArgs)
			r, err := GetTriggerUrl(ctx, &args, opts...)
			var s GetTriggerUrlResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetTriggerUrlResultOutput)
}

// A collection of arguments for invoking getTriggerUrl.
type GetTriggerUrlOutputArgs struct {
	// Example identifier
	FunctionName pulumi.StringInput `pulumi:"functionName"`
	// Example configurable attribute
	ServiceName pulumi.StringInput `pulumi:"serviceName"`
	// Example identifier
	TriggerName pulumi.StringInput `pulumi:"triggerName"`
}

func (GetTriggerUrlOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTriggerUrlArgs)(nil)).Elem()
}

// A collection of values returned by getTriggerUrl.
type GetTriggerUrlResultOutput struct{ *pulumi.OutputState }

func (GetTriggerUrlResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTriggerUrlResult)(nil)).Elem()
}

func (o GetTriggerUrlResultOutput) ToGetTriggerUrlResultOutput() GetTriggerUrlResultOutput {
	return o
}

func (o GetTriggerUrlResultOutput) ToGetTriggerUrlResultOutputWithContext(ctx context.Context) GetTriggerUrlResultOutput {
	return o
}

func (o GetTriggerUrlResultOutput) Config() pulumi.StringOutput {
	return o.ApplyT(func(v GetTriggerUrlResult) string { return v.Config }).(pulumi.StringOutput)
}

func (o GetTriggerUrlResultOutput) CreationTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetTriggerUrlResult) string { return v.CreationTime }).(pulumi.StringOutput)
}

// Example identifier
func (o GetTriggerUrlResultOutput) FunctionName() pulumi.StringOutput {
	return o.ApplyT(func(v GetTriggerUrlResult) string { return v.FunctionName }).(pulumi.StringOutput)
}

// The ID of this resource.
func (o GetTriggerUrlResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetTriggerUrlResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetTriggerUrlResultOutput) InvocationRole() pulumi.StringOutput {
	return o.ApplyT(func(v GetTriggerUrlResult) string { return v.InvocationRole }).(pulumi.StringOutput)
}

func (o GetTriggerUrlResultOutput) LastModificationTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetTriggerUrlResult) string { return v.LastModificationTime }).(pulumi.StringOutput)
}

// Example configurable attribute
func (o GetTriggerUrlResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v GetTriggerUrlResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

func (o GetTriggerUrlResultOutput) SourceArn() pulumi.StringOutput {
	return o.ApplyT(func(v GetTriggerUrlResult) string { return v.SourceArn }).(pulumi.StringOutput)
}

// Example identifier
func (o GetTriggerUrlResultOutput) TriggerName() pulumi.StringOutput {
	return o.ApplyT(func(v GetTriggerUrlResult) string { return v.TriggerName }).(pulumi.StringOutput)
}

func (o GetTriggerUrlResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetTriggerUrlResult) string { return v.Type }).(pulumi.StringOutput)
}

func (o GetTriggerUrlResultOutput) UrlInternet() pulumi.StringOutput {
	return o.ApplyT(func(v GetTriggerUrlResult) string { return v.UrlInternet }).(pulumi.StringOutput)
}

func (o GetTriggerUrlResultOutput) UrlIntranet() pulumi.StringOutput {
	return o.ApplyT(func(v GetTriggerUrlResult) string { return v.UrlIntranet }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetTriggerUrlResultOutput{})
}
