// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Example data source
 */
export function getTriggerUrl(args: GetTriggerUrlArgs, opts?: pulumi.InvokeOptions): Promise<GetTriggerUrlResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("alicloud-fc-url:index/getTriggerUrl:getTriggerUrl", {
        "functionName": args.functionName,
        "serviceName": args.serviceName,
        "triggerName": args.triggerName,
    }, opts);
}

/**
 * A collection of arguments for invoking getTriggerUrl.
 */
export interface GetTriggerUrlArgs {
    /**
     * Example identifier
     */
    functionName: string;
    /**
     * Example configurable attribute
     */
    serviceName: string;
    /**
     * Example identifier
     */
    triggerName: string;
}

/**
 * A collection of values returned by getTriggerUrl.
 */
export interface GetTriggerUrlResult {
    readonly config: string;
    readonly creationTime: string;
    /**
     * Example identifier
     */
    readonly functionName: string;
    /**
     * The ID of this resource.
     */
    readonly id: string;
    readonly invocationRole: string;
    readonly lastModificationTime: string;
    /**
     * Example configurable attribute
     */
    readonly serviceName: string;
    readonly sourceArn: string;
    /**
     * Example identifier
     */
    readonly triggerName: string;
    readonly type: string;
    readonly urlInternet: string;
    readonly urlIntranet: string;
}
/**
 * Example data source
 */
export function getTriggerUrlOutput(args: GetTriggerUrlOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetTriggerUrlResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("alicloud-fc-url:index/getTriggerUrl:getTriggerUrl", {
        "functionName": args.functionName,
        "serviceName": args.serviceName,
        "triggerName": args.triggerName,
    }, opts);
}

/**
 * A collection of arguments for invoking getTriggerUrl.
 */
export interface GetTriggerUrlOutputArgs {
    /**
     * Example identifier
     */
    functionName: pulumi.Input<string>;
    /**
     * Example configurable attribute
     */
    serviceName: pulumi.Input<string>;
    /**
     * Example identifier
     */
    triggerName: pulumi.Input<string>;
}
